server:
  port: "3001"
  max_connections: 200
  max_message_size: 4096

redis:
  addr: "redis:6379"  # Use "localhost:6379" for local development
  password: ""
  db: 0
  channel: "chat:messages"

database:
  host: "postgres"  # Use "localhost" for local development
  port: 5432
  user: "asocial"
  password: "asocial_dev_password"
  dbname: "asocial"
  sslmode: "disable"  # Use "require" for production

auth:
  firebase_credentials_path: ""  # Set to path of Firebase service account JSON in production
  app_url: "http://localhost"