apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: asocial
data:
  config.yaml: |
    server:
      port: "3001"
      max_connections: 200
      max_message_size: 4096

    redis:
      addr: "redis:6379"
      password: ""
      db: 0
      channel: "chat:messages"
