apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: asocial
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: backend
