apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: asocial

resources:
  - ../../base

# Production secret MUST be created manually before applying this
# DO NOT commit secret files to this directory
# See README.md for instructions
