apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: asocial
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: frontend
