// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"asocial/pkg/chat"
	"asocial/pkg/common"
	"asocial/pkg/config"
)

// Injectors from wire.go:

func InitializeChatServer(name string) (*common.Server, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	engine := chat.NewGinServer()
	melodyChatConn := chat.NewMelodyChatConn(configConfig)
	httpServer := chat.NewHttpServer(name, configConfig, engine, melodyChatConn)
	router := chat.NewRouter(httpServer)
	server := common.NewServer(name, router)
	return server, nil
}
