apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: asocial

resources:
  - ../../base
  - secret.yaml

# Use dev secret for local development
# Password: asocial_dev_password (WEAK - for minikube only)
